#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    udevadm control --reload-rules 2>/dev/null || true
    systemctl daemon-reload 2>/dev/null || true
    systemctl try-restart fprintd.service 2>/dev/null || true
fi

#DEBHELPER#

exit 0
